### ISSUE TITLE
Programma hangt bij bepaald gebruik deobjectify fact type

### ISSUE THREAD

**Issue by JBerkvens** [SymbiosisGroup/Tool#15]
Als men in het object model voor een requirement Deobjectify fact type selecteert, en tekst aan de bovenkant verwijdert, hangt het programma.
Dus bijvoorbeeld bij de requirement "In country : Country they speak language : Language", als men bij deobjectify het woordje 'In' of een gedeelte hiervan weghaalt, hangt het programma bij het confirmeren van de deobjectificatie.

**Comment by FrankPeeters** [comment]
Het bovengenoemde feittype is kennelijk eerst geobjectiveerd. Als ik dat feittype vervolgens deobjectiveer en de eerste constante aanpas, hangt het programma niet...
