### ISSUE TITLE
Selectie van optie 'Cancel' bij rolwijziging zorgt voor geen actieve rol

### ISSUE THREAD

**Issue by JBerkvens** [SymbiosisGroup/Tool#20]
Als een gebruiker van rol wil wijzigen, maar van gedachten veranderd en op Cancel drukt, zou de huidig actieve gebruiker actief moeten blijven. 
Het programma deactiveert de gebruiker echter en gaat naar '?', er is dus geen gebruiker meer actief. Deze moet eerst weer geselecteerd worden voordat het programma verder kan worden gebruikt.

**Comment by 304868** [comment]
Lijkt alsof dit gefixed is, maar nu is een nieuw probleem mee. Als je Change Current User doet, verandert het programma automatisch de huidige user naar de andere. Als je dan op Cancel drukt of het venster sluit, is de user gewijzigd hoewel dat misschien helemaal niet de bedoeling is.

**Comment by FrankPeeters** [comment]
geschetste probleem van Nadiv is verwijderd.
